[package]
name = "haiku-generator"
version = "0.0.2"
authors = ["Loïc TRUCHOT"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
unicode-segmentation = "1.6.0"
